---
- hosts: database
  become: true
  tasks:
    - name: install tools
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - python-mysqldb

    - name: Install mysql-server
      apt: name=mysql-server state=present update_cache=yes
    
    - name: ensure mysql running
      service: name=mysql state=started enabled=yes

    - name: ensure mysql listning on all ports√ü
      lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address
                  line="bind-address = 0.0.0.0"
      notify: restart mysql

    - name: create database
      mysql_db: name=demo state=present 

    - name: create mysql user
      mysql_user: name=demo password=demo priv=demo.*:ALL host='$' state=present
  
  handlers: 
    - name: restart mysql
      service: name=mysql state=restarted
