---
- hosts: loadbalancer
  become: true
  tasks:
    - service: name=nginx state=stopped

- hosts: webserver
  become: true
  tasks:
    - service: name=apapche2 state=stopped

- hosts: database
  become: true
  tasks:
    - service: name=mysql state=restarted

- hosts: webserver
  become: true
  tasks:
    - service: name=apapche2 state=start

- hosts: loadbalancer
  become: true
  tasks:
    - service: name=nginx state=start