---
- hosts: loadbalancer
  become: true
  tasks:
    - name: verify nginx servive
      command: service nginx status

    - name: verify nginx is running on port 80
      wait_for: port=80 timeout=1

- hosts: webserver
  become: true
  tasks:
    - name: verify apache2 servive
      command: service apache2 status

    - name: verify apache2 is running on port 80
      wait_for: port=80 timeout=1

- hosts: database
  become: true
  tasks:
    - name: verify mysql servive
      command: service mysql status

    - name: verify mysql is running on port 3306
      wait_for: port=3306 timeout=1

- hosts: control
  tasks:
    - name: verify end-to-end resopnse
      uri: url=http://{{item}} return_content=yes
      with_items: "{{groups.loadbalancer}}"
      register: lb_index

    - fail: msg="index failed to return content"
      when: "'Hello, from sunny' not in item.content"
      with_items: "{{lb_index.results}}"

- hosts: loadbalancer
  tasks:
    - name: verify backend resopnse
      uri: url=http://{{item}} return_content=yes
      with_items: groups.webserver
      register: app_index

    - fail: msg="index failed to return content"
      when: "'Hello, from sunny {{item.iten}}!' not in item.content"
      with_items: "{{app_index.results}}"