---
- hosts: webserver
  become: true
  tasks:
    - name: Install Apache2
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - apache2
        - libapache2-mod-wsgi
        - python-pip
        - python-virtualenv

    - name: ensure apache2 started
      service: name=apache2 state=started enabled=yes

    - name: ensure wsgi enabled
      apache2_module: name=wsgi state=present
      notify: restart apache2

    - name: copy demo app source
      copy: src=demo/app/ dest=/var/www/html/demo mod=0755
      notify: restart apache2

    - name: Copy apache virtual host conf
      copy: src=demo/demo.conf dest=/etc/apache2/sites-available mod=0755
      notify: restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
   